### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by TarekTaha** [kylewray/lpomdp#1]
How do you build this library, and what are the dependencies ?

**Comment by kylewray** [comment]
You need to download the other projects entitled "losm" and "librbr". The latter depends on COIN-OR. I used Eclipse for these projects, so it might be easier to do the same. You can compile all of them in Eclipse.

Personally, I would recommend using this code as a reference, rather than using it directly. If you need a POMDP solver, feel free to checkout my library "nova".
